### PR TITLE
Remove duplicate link in the Packages section

### PR DESCRIPTION
**Pull request by svenluijten**

### CODE REVIEW

**Comment by kirschbaum** [comment]
@svenluijten this is not a duplicate link. Could you provide more details?

**Comment by svenluijten** [comment]
Sure:

screenshot

Both links go to [the same page](https://github.com/kirschbaum/laravel-spark-pages).

**Comment by kirschbaum** [comment]
@svenluijten Ah, you are correct sir! Should have had my morning coffee first :)

**Comment by svenluijten** [comment]
Hehe, no worries :-)

**Comment by jpmurray** [comment]
Good catch! :)

**Pull request merged**
